name: "Generate Files"

on:
  push:
    branches:
      - main

jobs:
  process:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4.0.0
        with:
          python-version: 3.8

      - name: process
        run: |
          echo "-------- install requirements --------"
          pip install matplotlib==3.5.2
          pip install seaborn==0.11.2
          pip install pyyaml==6.0
          echo "-------- start processing --------"
          python3 main.py
          echo "-------- push to GitHub --------"
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add figures/*
          changes=`git status --porcelain`
          if [[ -z ${changes} ]]; then
            echo "no changes"
          else
            git commit -m "update figures"
          fi
          git add all_models.json
          changes=`git status --porcelain`
          JSON_COMMIT_SHA1=""
          if [[ -z ${changes} ]]; then
            echo "no changes"
          else
            git commit -m "update json file"
            JSON_COMMIT_SHA1=git rev-parse --short main
          fi
          git push -u origin main
          if [[ -z ${JSON_COMMIT_SHA1} ]]; then
            echo "no changes for gh_pages branch"
          else
            git checkout gh_pages
            git cherry-pick ${JSON_COMMIT_SHA1}
            git push -u origin gh_pages
          fi
